project_id = "yaincoxihiqdksxgrsrk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.generate-music]
verify_jwt = false

[functions.compare-official-content]
verify_jwt = false

[functions.extract-edn-uness-auth]
verify_jwt = false

[functions.test-edn-extraction]
verify_jwt = false

[functions.debug-uness-auth]
verify_jwt = false

[functions.extract-edn-uness-production]
verify_jwt = false

[functions.test-login]
verify_jwt = false

[functions.test-cas-simple]
verify_jwt = false