version: '3.8'

services:
  # Development overrides
  api:
    command: pnpm run dev:api
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - ./node_modules:/app/node_modules

  worker:
    command: pnpm run dev:worker
    volumes:
      - ./apps/worker:/app/apps/worker
      - ./packages:/app/packages
      - ./node_modules:/app/node_modules

  # Additional dev services
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
