export const ROUTE_PATHS = {
  home: '/',
  modularDashboard: '/modular-dashboard',
  dashboard: '/dashboard',
  learningDashboard: '/learning-dashboard',
  platformStatus: '/platform-status',
  monitoring: '/monitoring',
  systemManagement: '/system-management',
  platformSettings: '/platform-settings',
  optimizedIndex: '/optimized',
  generator: '/generator',
  sharedMusic: '/shared-music/:trackId',
  sharedMusicIndex: '/shared-music',
  ednComplete: '/edn-complete',
  ednCompleteDetail: '/edn-complete/:slug',
  ednImmersive: '/edn/:slug/immersive',
  ednMusicLibrary: '/edn/music-library',
  ecosIndex: '/ecos',
  ecosScenario: '/ecos/:scenarioId',
  store: '/store',
  productDetail: '/product/:handle',
  audit: '/audit',
  auditCompleteness: '/audit-completeness',
  migrationDashboard: '/migration-dashboard',
  mngMethod: '/mng-method',
  mentionsLegales: '/mentions-legales',
  politiqueConfidentialite: '/politique-confidentialite',
  cgu: '/cgu',
  declarationAccessibilite: '/declaration-accessibilite',
  medMngLogin: '/med-mng/login',
  medMngSignup: '/med-mng/signup',
  medMngPricing: '/med-mng/pricing',
  medMngSubscribe: '/med-mng/subscribe/:planId',
  medMngSuccess: '/med-mng/success',
  medMngCreate: '/med-mng/create',
  medMngResetPassword: '/med-mng/reset-password',
  medMngLibrary: '/med-mng/library',
  medMngMusicLibrary: '/med-mng/music-library',
  medMngItemsLibrary: '/med-mng/items-library',
  medMngItemDetail: '/med-mng/items/:itemCode',
  medMngProfile: '/med-mng/profile',
  medMngPlayer: '/med-mng/player/:songId',
  medMngPlaylists: '/med-mng/playlists',
  medMngPlaylistDetail: '/med-mng/playlists/:playlistId',
  medMngAnalytics: '/med-mng/analytics',
  medMngProgress: '/med-mng/progress',
  medMngFavorites: '/med-mng/favorites',
  chat: '/chat',
  ednAudit: '/edn-audit',
  adminImport: '/admin/import',
  adminAudit: '/admin/audit',
  adminExtractEdn: '/admin/extract-edn',
  adminExtractEcos: '/admin/extract-ecos',
  adminExtractObjectifs: '/admin/extract-objectifs',
  adminOicQuality: '/admin/oic-quality',
  adminExtractionQuality: '/admin/extraction-quality',
  adminComplete: '/admin/complete',
  adminPanel: '/admin-panel',
  library: '/library',
  accessibilityDashboard: '/accessibility-dashboard',
  effectivenessDashboard: '/effectiveness-dashboard',
  rlsDocumentation: '/rls-documentation',
  securityMonitoring: '/security-monitoring',
  statistics: '/statistics',
  studyPlanner: '/study-planner',
  community: '/community',
  homepage: '/homepage',
  achievements: '/achievements',
  favorites: '/favorites',
  settings: '/settings',
  designSystem: '/design-system',
  mesDonneesRgpd: '/mes-donnees-rgpd',
  installPwa: '/install',
  pwaAnalytics: '/pwa-analytics',
  diagnostics: '/diagnostics',
  ednLegacy: '/edn',
  ednLegacyWithSlug: '/edn/:slug',
  ednItemsLegacy: '/items-edn',
  auditGeneral: '/audit-general',
  auditEdn: '/audit-edn',
  auditUnified: '/audit-unified',
  auditIc1: '/audit-ic1',
  auditIc2: '/audit-ic2',
  auditIc4: '/audit-ic4',
  auditCompleteLegacy: '/audit-complete',
  srsReview: '/srs-review',
  examMode: '/exam-mode',
  clinicalCases: '/clinical-cases',
  flashcards: '/flashcards',
  progressDashboard: '/progress-dashboard',
  smartStudyPlanner: '/smart-study-planner',
  // Nouvelles pages prioritaires
  leaderboard: '/leaderboard',
  dailyChallenges: '/daily-challenges',
  myGoals: '/my-goals',
  moodTracker: '/mood-tracker',
  pomodoro: '/pomodoro',
  karaoke: '/karaoke/:songId?',
  executiveDashboard: '/executive-dashboard',
  // Démo publique
  demo: '/demo',
  // Raccourcis publics
  createShortcut: '/create',
  notFound: '*',
} as const;

export const ROUTE_REDIRECTS = [
  ROUTE_PATHS.ednLegacy,
  ROUTE_PATHS.ednLegacyWithSlug,
  ROUTE_PATHS.ednItemsLegacy,
  ROUTE_PATHS.auditGeneral,
  ROUTE_PATHS.auditEdn,
  ROUTE_PATHS.auditUnified,
  ROUTE_PATHS.auditIc1,
  ROUTE_PATHS.auditIc2,
  ROUTE_PATHS.auditIc4,
  ROUTE_PATHS.auditCompleteLegacy,
  ROUTE_PATHS.optimizedIndex, // Redirige vers home
  ROUTE_PATHS.homepage, // Redirige vers home
] as const;

export const ROUTE_LIST = Object.values(ROUTE_PATHS);

export const ALL_KNOWN_ROUTES: readonly string[] = [
  ...ROUTE_LIST,
  ...ROUTE_REDIRECTS,
];
