
-- Ajouter l'item 3 sur le raisonnement et la décision en médecine (correction finale)
INSERT INTO public.edn_items_immersive (
  item_code,
  slug,
  title,
  subtitle,
  pitch_intro
) VALUES (
  'IC-3',
  'ic-3-raisonnement-decision-medecine',
  'Raisonnement et décision en médecine',
  'Maîtriser les fondements de la décision médicale éclairée',
  'La médecine moderne exige du praticien une capacité à raisonner de manière structurée et à prendre des décisions éclairées. De la médecine basée sur les preuves aux différents styles de raisonnement clinique, ce parcours vous guide à travers les concepts essentiels pour une pratique médicale réfléchie et adaptée à chaque patient.'
);

-- Mise à jour avec les données JSON
UPDATE public.edn_items_immersive 
SET 
  tableau_rang_a = '{"theme": "Raisonnement et décision en médecine - Rang A", "colonnes": ["Concept", "Définition", "Application pratique"], "lignes": [["Médecine basée sur les preuves (EBM)", "Utilisation consciencieuse et judicieuse des meilleures données scientifiques actuelles dans la prise en charge personnalisée de chaque patient", "Intégration de l''expérience clinique, des données scientifiques récentes et des préférences du patient"], ["Démarche EBM - PICOT", "Patients, Intervention, Comparator, Outcomes, Time - Structure pour formuler une question clinique claire", "Convertir le problème clinique en question précise avec tous les éléments nécessaires"], ["Styles de raisonnement", "Différentes approches pour analyser une situation clinique", "Reconnaissance archétypale, méthode hypothético-déductive, mode intuitif, démarche algorithmique"], ["Examens complémentaires", "4 catégories : Imagerie, Analyses biologiques, Endoscopie, Épreuves fonctionnelles", "Prescription réfléchie basée sur probabilité post-test, risques, coût et conséquences"], ["Décision partagée", "Le professionnel et le patient partagent l''information médicale et effectuent un choix éclairé mutuellement accepté", "Alternative au modèle paternaliste, respect des préférences du patient"], ["Personne de confiance", "Personne désignée pour être consultée si le patient est hors d''état d''exprimer sa volonté", "Témoigne de l''expression de la volonté, son témoignage prévaut sur tout autre"]]}',
  tableau_rang_b = '{"theme": "Raisonnement et décision en médecine - Rang B", "colonnes": ["Concept avancé", "Explication", "Enjeux pratiques"], "lignes": [["Supports au raisonnement clinique", "Motifs multiples (2,6 par consultation), intrication chronique/aigu, adaptation aux priorités", "Prévention quaternaire - éviter bilans et filières déraisonnables"], ["Bases d''information", "SFMG : fiches de risques critiques évitables, HAS : fiches de transparence avec SMR", "Baliser les bénéfices/risques des interventions médicales"], ["Logique thérapeutique", "Nommer la situation clinique, décider de façon négociée selon situation, préférences patient, caractéristiques médecin", "Démarche médicale intégrée et personnalisée"], ["Efficacité vs Effectivité vs Efficience", "Efficacité théorique vs pratique vs optimisation des ressources", "Outils : ratio bénéfice/risque, coût/efficacité, méta-analyses"], ["Analyse décisionnelle", "Technique de modélisation décomposant problèmes complexes en loteries élémentaires", "Arbre de décision, utilité moyenne pondérée par probabilités"], ["Dynamiques décisionnelles", "Équilibre entre art médical, données scientifiques et préférences patient", "Éviter paternalisme, scientisme ou négligence des preuves"], ["Systèmes d''aide à la décision (SADM)", "Applications logicielles fournissant informations cliniques filtrées au moment opportun", "Clinical Decision Support Systems pour faciliter la prise en charge"]]}',
  scene_immersive = '{"setting": "Cabinet médical moderne", "characters": [{"name": "Dr. Martin", "role": "Médecin généraliste", "description": "Praticien expérimenté qui maîtrise les outils de décision médicale"}, {"name": "Mme Dubois", "role": "Patiente", "description": "Patiente avec symptômes complexes nécessitant une approche structurée"}], "scenario": "Face à des symptômes non spécifiques, le Dr. Martin applique une démarche de médecine basée sur les preuves, formulant des questions PICOT, évaluant les données disponibles et impliquant la patiente dans une décision partagée pour établir la meilleure stratégie diagnostique et thérapeutique."}',
  paroles_musicales = ARRAY['[Couplet 1] Dans le flot des données, le médecin navigue Entre preuves et doutes, sa sagesse se guide PICOT en main, questions bien formulées Pour que chaque patient soit mieux soigné [Refrain] EBM, Evidence-Based Medicine Science et art, une même discipline Du paternalisme à la décision partagée L''humanité au cœur de la médecine', '[Couplet 2] Hypothético-déductif, le raisonnement s''affine Archétype ou intuition, chaque cas se devine Examens complémentaires, quatre grandes familles Pour éclairer le diagnostic, sans se perdre dans l''oubli [Pont] Efficacité, effectivité, efficience Trois concepts pour guider notre science L''analyse décisionnelle, arbre de probabilité Pour que la médecine reste humanité'],
  interaction_config = '{"type": "classification", "title": "Associez les concepts aux bonnes définitions", "categories": [{"name": "Démarche EBM", "items": ["PICOT", "Revue systématique", "Méta-analyse", "Niveaux de preuve"]}, {"name": "Styles de raisonnement", "items": ["Reconnaissance archétypale", "Hypothético-déductif", "Mode intuitif", "Démarche algorithmique"]}, {"name": "Types de décision", "items": ["Décision partagée", "Modèle paternaliste", "Décision collégiale", "Personne de confiance"]}]}',
  quiz_questions = '{"type": "classification", "title": "Associez les concepts aux bonnes définitions", "categories": [{"name": "Démarche EBM", "items": ["PICOT", "Revue systématique", "Méta-analyse", "Niveaux de preuve"]}, {"name": "Styles de raisonnement", "items": ["Reconnaissance archétypale", "Hypothético-déductif", "Mode intuitif", "Démarche algorithmique"]}, {"name": "Types de décision", "items": ["Décision partagée", "Modèle paternaliste", "Décision collégiale", "Personne de confiance"]}]}',
  reward_messages = '{"completion": "Félicitations ! Vous maîtrisez maintenant les fondements du raisonnement et de la décision en médecine.", "badge": "Expert en décision médicale", "message": "De la médecine basée sur les preuves aux systèmes d''aide à la décision, vous avez acquis les outils essentiels pour une pratique médicale éclairée et centrée sur le patient."}'
WHERE item_code = 'IC-3';
