-- Ajout des colonnes pour les paroles par rang (si elles n'existent pas déjà)
ALTER TABLE edn_items_immersive 
ADD COLUMN IF NOT EXISTS paroles_rang_a TEXT[],
ADD COLUMN IF NOT EXISTS paroles_rang_b TEXT[],
ADD COLUMN IF NOT EXISTS paroles_rang_ab TEXT[];

-- Mettre à jour les paroles pour IC-1 comme exemple
UPDATE edn_items_immersive 
SET 
  paroles_rang_a = ARRAY[
    '[Couplet 1 - Rang A]',
    'Item IC-1 je vais maîtriser',
    'La relation médecin-malade étudier',
    'Communication et empathie à développer',
    'Les bases solides pour réussir',
    '',
    '[Refrain]',
    'EDN IC-1 chantons ensemble',
    'Compétences Rang A qui se rassemblent',
    'Pour l''examen on se prépare',
    'Avec la musique tout devient plus claire',
    '',
    '[Couplet 2 - Rang A]',
    'Chaque concept je vais comprendre',
    'Les définitions bien apprendre',
    'Écoute active et bienveillance',
    'Pour mes patients excellence',
    '',
    '[Refrain]',
    'EDN IC-1 chantons ensemble',
    'Compétences Rang A qui se rassemblent',
    'Pour l''examen on se prépare',
    'Avec la musique tout devient plus claire',
    '',
    '[Partie 3 - Synthèse Rang A]',
    'Maintenant je maîtrise les bases',
    'De la relation médecin-malade les traces',
    'Rang A conquis avec assurance',
    'Place à l''excellence et à la performance',
    '',
    '[Refrain Final]',
    'Item IC-1 Rang A validé',
    'Connaissances solides intégrées',
    'Vers le rang B je vais progresser',
    'En musique médecine et réussite mélangées'
  ],
  paroles_rang_b = ARRAY[
    '[Couplet 1 - Rang B]',
    'Rang B de l''item IC-1 expert je deviens',
    'La relation médecin-malade je maîtrise enfin',
    'Situations complexes à gérer',
    'Communication avancée à maîtriser',
    '',
    '[Refrain]',
    'Expertise IC-1 niveau supérieur',
    'Compétences avancées pour aller de l''avant',
    'Rang B c''est la maîtrise parfaite',
    'Excellence clinique qui se reflète',
    '',
    '[Couplet 2 - Rang B]',
    'Techniques pointues je développe',
    'Situations difficiles je surmonte',
    'Innovation et précision',
    'Au service de ma mission',
    '',
    '[Refrain]',
    'Expertise IC-1 niveau supérieur',
    'Compétences avancées pour aller de l''avant',
    'Rang B c''est la maîtrise parfaite',
    'Excellence clinique qui se reflète',
    '',
    '[Partie 3 - Excellence Rang B]',
    'Spécialiste confirmé je suis',
    'De la communication l''esprit',
    'Rang B maîtrisé avec brio',
    'Expert reconnu, mission accomplie',
    '',
    '[Refrain Final]',
    'Item IC-1 expertise atteinte',
    'Rang B validé, compétence certaine',
    'Excellence clinique démontrée',
    'Médecine et musique réconciliées'
  ],
  paroles_rang_ab = ARRAY[
    '[Couplet 1 - Fusion A+B]',
    'Item IC-1 du rang A au rang B',
    'Parcours complet de A à Z',
    'Des bases jusqu''à l''expertise',
    'Maîtrise totale garantie',
    '',
    '[Refrain]',
    'A plus B égale excellence',
    'Compétences totales en évidence',
    'Fusion parfaite des savoirs',
    'Pour un succès sans égal',
    '',
    '[Couplet 2 - Complémentarité]',
    'Rang A donne les fondations',
    'Rang B apporte innovations',
    'Ensemble ils forment un tout',
    'Expertise sans aucun tabou',
    '',
    '[Refrain]',
    'A plus B égale excellence',
    'Compétences totales en évidence',
    'Fusion parfaite des savoirs',
    'Pour un succès sans égal',
    '',
    '[Partie 3 - Synthèse Complète]',
    'De la relation médecin-malade je sais tout',
    'Compétences complètes partout',
    'A et B unis pour la réussite',
    'Médecin expert accompli',
    '',
    '[Refrain Final]',
    'Item IC-1 maîtrise totale',
    'A+B fusion magistrale',
    'Excellence complète atteinte',
    'Succès EDN mérité'
  ]
WHERE item_code = 'IC-1';