-- Mise à jour complète de tous les titres des items EDN avec les intitulés officiels
UPDATE edn_items_immersive 
SET title = CASE item_code
  WHEN 'IC-1' THEN 'La relation médecin-malade dans le cadre du colloque singulier ou au sein d''une équipe, le cas échéant pluriprofessionnelle. La communication avec le patient et son entourage. L''annonce d''une maladie grave ou létale ou d''un dommage associé aux soins. La formation du patient. La personnalisation de la prise en charge médicale.'
  WHEN 'IC-2' THEN 'Les valeurs professionnelles du médecin et des autres professions de santé'
  WHEN 'IC-3' THEN 'Le raisonnement et la décision en médecine. La médecine fondée sur les preuves (Evidence Based Medicine, EBM). La décision médicale partagée. La controverse.'
  WHEN 'IC-4' THEN 'Qualité et sécurité des soins. La sécurité du patient. La gestion des risques. Les événements indésirables associés aux soins (EIAS). Démarche qualité et évaluation des pratiques professionnelles'
  WHEN 'IC-5' THEN 'La gestion des erreurs et des plaintes ; l''aléa thérapeutique'
  WHEN 'IC-6' THEN 'L''organisation de l''exercice clinique et les méthodes qui permettent de sécuriser le parcours du patient'
  WHEN 'IC-7' THEN 'Les droits individuels et collectifs du patient'
  WHEN 'IC-8' THEN 'Les discriminations'
  WHEN 'IC-9' THEN 'Introduction à l''éthique médicale'
  WHEN 'IC-10' THEN 'Approches transversales du corps'
  WHEN 'IC-11' THEN 'Violences et santé.'
  WHEN 'IC-12' THEN 'Violences sexuelles'
  WHEN 'IC-13' THEN 'Certificats médicaux. Décès et législation.'
  WHEN 'IC-14' THEN 'La mort'
  WHEN 'IC-15' THEN 'Soins psychiatriques sans consentement'
  WHEN 'IC-16' THEN 'Organisation du système de soins. Sa régulation. Les indicateurs. Parcours de soins.'
  WHEN 'IC-17' THEN 'Télémédecine, télésanté et téléservices en santé.'
  WHEN 'IC-18' THEN 'Santé et numérique'
  WHEN 'IC-19' THEN 'La sécurité sociale. L''assurance maladie. Les assurances complémentaires. La complémentaire santé solidaire (CSS). La consommation médicale. Protection sociale. Consommation médicale et économie de la santé.'
  WHEN 'IC-20' THEN 'La méthodologie de la recherche en santé'
  WHEN 'IC-21' THEN 'Mesure de l''état de santé de la population'
  WHEN 'IC-22' THEN 'Maladies rares'
  WHEN 'IC-23' THEN 'Grossesse normale'
  WHEN 'IC-24' THEN 'Principales complications de la grossesse'
  WHEN 'IC-25' THEN 'Grossesse extra-utérine'
  WHEN 'IC-26' THEN 'Douleur abdominale aiguë chez une femme enceinte'
  WHEN 'IC-27' THEN 'Prévention des risques fœtaux : infection, médicaments, toxiques, irradiation'
  WHEN 'IC-28' THEN 'Connaître les particularités de l''infection urinaire au cours de la grossesse'
  WHEN 'IC-29' THEN 'Connaître les principaux risques professionnels pour la maternité, liés au travail de la mère.'
  WHEN 'IC-30' THEN 'Prématurité et retard de croissance intra-utérin : facteurs de risque et prévention'
  WHEN 'IC-31' THEN 'Accouchement, délivrance et suites de couches normales'
  WHEN 'IC-32' THEN 'Évaluation et soins du nouveau-né à terme'
  WHEN 'IC-33' THEN 'Allaitement maternel'
  WHEN 'IC-34' THEN 'Suites de couches pathologiques : pathologie maternelle dans les 40 jours'
  WHEN 'IC-35' THEN 'Anomalies du cycle menstruel. Métrorragies'
  WHEN 'IC-36' THEN 'Contraception'
  WHEN 'IC-37' THEN 'Interruption volontaire de grossesse'
  WHEN 'IC-38' THEN 'Infertilité du couple : conduite de la première consultation'
  WHEN 'IC-39' THEN 'Assistance médicale à la procréation : principaux aspects biologiques, médicaux et éthiques'
  WHEN 'IC-40' THEN 'Algies pelviennes chez la femme'
  WHEN 'IC-41' THEN 'Endométriose'
  WHEN 'IC-42' THEN 'Aménorrhée'
  WHEN 'IC-43' THEN 'Hémorragie génitale chez la femme'
  WHEN 'IC-44' THEN 'Tuméfaction pelvienne chez la femme'
  WHEN 'IC-45' THEN 'Spécificités des maladies génétiques'
  WHEN 'IC-46' THEN 'Médecine génomique'
  WHEN 'IC-47' THEN 'Suivi d''un nourrisson, d''un enfant et d''un adolescent normal. Dépistage des anomalies orthopédiques, des troubles visuels, auditifs et dentaires. Examens de santé obligatoires. Médecine scolaire. Mortalité et morbidité infantiles.'
  WHEN 'IC-48' THEN 'Alimentation et besoins nutritionnels du nourrisson et de l''enfant'
  WHEN 'IC-49' THEN 'Puberté normale et pathologique'
  WHEN 'IC-50' THEN 'Pathologie génito-scrotale chez le garçon et chez l''homme'
  WHEN 'IC-51' THEN 'Troubles de la miction chez l''enfant'
  WHEN 'IC-52' THEN 'Strabisme et amblyopie de l''enfant'
  WHEN 'IC-53' THEN 'Retard de croissance staturo-pondérale'
  WHEN 'IC-54' THEN 'Boiterie chez l''enfant'
  WHEN 'IC-55' THEN 'Développement psychomoteur du nourrisson et de l''enfant'
  WHEN 'IC-56' THEN 'L''enfant handicapé : orientation et prise en charge'
  WHEN 'IC-57' THEN 'Maltraitance et enfants en danger. Protection maternelle et infantile'
  WHEN 'IC-58' THEN 'Sexualité normale et ses troubles'
  WHEN 'IC-59' THEN 'Sujets en situation de précarité'
  WHEN 'IC-60' THEN 'Connaître les facteurs de risque, prévention, dépistage des troubles psychiques de l''enfant à la personne âgée'
  WHEN 'IC-61' THEN 'Connaître les bases des classifications des troubles mentaux de l''enfant à la personne âgée'
  WHEN 'IC-62' THEN 'Décrire l''organisation de l''offre de soins en psychiatrie, de l''enfant à la personne âgée'
  WHEN 'IC-63' THEN 'Trouble schizophrénique'
  WHEN 'IC-64' THEN 'Trouble bipolaire'
  WHEN 'IC-65' THEN 'Trouble délirant persistant'
  WHEN 'IC-66' THEN 'Diagnostiquer : un trouble dépressif, un trouble anxieux généralisé, un trouble panique, un trouble phobique, un trouble obsessionnel compulsif, un état de stress post-traumatique, un trouble de l''adaptation (de l''enfant à la personne âgée), un trouble de la personnalité.'
  WHEN 'IC-67' THEN 'Troubles envahissants du développement'
  WHEN 'IC-68' THEN 'Troubles du comportement de l''adolescent'
  WHEN 'IC-69' THEN 'Troubles psychiques de la grossesse et du post-partum'
  WHEN 'IC-70' THEN 'Troubles psychiques du sujet âgé'
  WHEN 'IC-71' THEN 'Troubles des conduites alimentaires chez l''adolescent et l''adulte'
  WHEN 'IC-72' THEN 'Troubles à symptomatologie somatique et apparentés à tous les âges'
  WHEN 'IC-73' THEN 'Différents types de techniques psychothérapeutiques'
  WHEN 'IC-74' THEN 'Prescription et surveillance des psychotropes'
  WHEN 'IC-75' THEN 'Addiction au tabac.'
  WHEN 'IC-76' THEN 'Addiction à l''alcool.'
  WHEN 'IC-77' THEN 'Addiction aux médicaments psychotropes (benzodiazépines et apparentés)'
  WHEN 'IC-78' THEN 'Addiction au cannabis, à la cocaïne, aux amphétamines, aux opiacés, aux drogues de synthèse'
  WHEN 'IC-79' THEN 'Addictions comportementales'
  WHEN 'IC-80' THEN 'Dopage et conduites dopantes'
  WHEN 'IC-81' THEN 'Altération chronique de la vision'
  WHEN 'IC-82' THEN 'Altération aiguë de la vision'
  WHEN 'IC-83' THEN 'Infections et inflammations oculaires'
  WHEN 'IC-84' THEN 'Glaucomes'
  WHEN 'IC-85' THEN 'Troubles de la réfraction'
  WHEN 'IC-86' THEN 'Pathologie des paupières'
  WHEN 'IC-87' THEN 'Epistaxis'
  WHEN 'IC-88' THEN 'Trouble aigu de la parole. Dysphonie'
  WHEN 'IC-89' THEN 'Altération de la fonction auditive'
  WHEN 'IC-90' THEN 'Pathologie des glandes salivaires'
  WHEN 'IC-91' THEN 'Déficit neurologique récent'
  WHEN 'IC-92' THEN 'Déficit moteur et/ou sensitif des membres'
  WHEN 'IC-93' THEN 'Compression médullaire non traumatique et syndrome de la queue de cheval'
  WHEN 'IC-94' THEN 'Rachialgie'
  WHEN 'IC-95' THEN 'Radiculalgie et syndrome canalaire'
  WHEN 'IC-96' THEN 'Neuropathies périphériques'
  WHEN 'IC-97' THEN 'Polyradiculonévrite aiguë inflammatoire (syndrome de Guillain-Barré)'
  WHEN 'IC-98' THEN 'Myasthénie'
  WHEN 'IC-99' THEN 'Migraine, névralgie du trijumeau et algies de la face'
  WHEN 'IC-100' THEN 'Céphalée inhabituelle aiguë et chronique chez l''adulte et l''enfant'
  WHEN 'IC-101' THEN 'Paralysie faciale'
  WHEN 'IC-102' THEN 'Diplopie'
  WHEN 'IC-103' THEN 'Vertige'
  WHEN 'IC-104' THEN 'Sclérose en plaques'
  WHEN 'IC-105' THEN 'Épilepsie de l''enfant et de l''adulte'
  WHEN 'IC-106' THEN 'Maladie de Parkinson'
  WHEN 'IC-107' THEN 'Mouvements anormaux'
  WHEN 'IC-108' THEN 'Confusion, démences'
  WHEN 'IC-109' THEN 'Troubles de la marche et de l''équilibre'
  WHEN 'IC-110' THEN 'Troubles du sommeil de l''enfant et de l''adulte'
  WHEN 'IC-111' THEN 'Dermatoses faciales : acné, rosacée, dermatite séborrhéique'
  WHEN 'IC-112' THEN 'Dermatose bulleuse touchant la peau et/ou les muqueuses externes'
  WHEN 'IC-113' THEN 'Hémangiomes et malformations vasculaires cutanées'
  WHEN 'IC-114' THEN 'Exanthème et érythrodermie de l''adulte et de l''enfant'
  WHEN 'IC-115' THEN 'Toxidermies'
  WHEN 'IC-116' THEN 'Prurit'
  WHEN 'IC-117' THEN 'Psoriasis'
  WHEN 'IC-118' THEN 'La personne handicapée : bases de l''évaluation fonctionnelle et thérapeutique'
  WHEN 'IC-119' THEN 'Soin et accompagnement dans la maladie chronique et le handicap'
  WHEN 'IC-120' THEN 'Complications de l''immobilité et du décubitus. Prévention et prise en charge'
  WHEN 'IC-121' THEN 'Le handicap psychique'
  WHEN 'IC-122' THEN 'Principales techniques de rééducation et de réadaptation'
  WHEN 'IC-123' THEN 'Vieillissement normal : aspects biologiques, fonctionnels et relationnels. Données épidémiologiques et sociologiques. Prévention du vieillissement pathologique'
  WHEN 'IC-124' THEN 'Ménopause, insuffisance ovarienne prématurée, andropause, déficit androgénique lié à l''âge'
  WHEN 'IC-125' THEN 'Troubles de la miction et incontinence urinaire de l''adulte et du sujet âgé'
  WHEN 'IC-126' THEN 'Trouble de l''érection'
  WHEN 'IC-127' THEN 'Hypertrophie bénigne de la prostate'
  WHEN 'IC-128' THEN 'Ostéopathies fragilisantes'
  WHEN 'IC-129' THEN 'Arthrose'
  WHEN 'IC-130' THEN 'La personne âgée malade : particularités sémiologiques, psychologiques et thérapeutiques'
  WHEN 'IC-131' THEN 'Troubles de la marche et de l''équilibre'
  WHEN 'IC-132' THEN 'Troubles cognitifs du sujet âgé'
  WHEN 'IC-133' THEN 'Autonomie et dépendance chez le sujet âgé'
  WHEN 'IC-134' THEN 'Bases neurophysiologiques, mécanismes physiopathologiques d''une douleur aiguë et d''une douleur chronique'
  WHEN 'IC-135' THEN 'Thérapeutiques antalgiques, médicamenteuses et non médicamenteuses'
  WHEN 'IC-136' THEN 'Anesthésie locale, locorégionale et générale'
  WHEN 'IC-137' THEN 'Douleur chez l''enfant : évaluation et traitements antalgiques'
  WHEN 'IC-138' THEN 'Douleur chez la personne vulnérable'
  WHEN 'IC-139' THEN 'Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (1). Principaux repères cliniques. Modalités d''organisation des équipes, en établissement de santé et en et en ambulatoire'
  WHEN 'IC-140' THEN 'Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (2). Accompagnement de la personne malade et de son entourage. Principaux repères éthiques.'
  WHEN 'IC-141' THEN 'Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (3). La sédation pour détresse en phase terminale et dans des situations spécifiques et complexes en fin de vie. Réponse à la demande d''euthanasie ou de suicide assisté.'
  WHEN 'IC-142' THEN 'Connaître les aspects spécifiques des soins palliatifs en pédiatrie'
  WHEN 'IC-143' THEN 'Connaître les aspects spécifiques des soins palliatifs en réanimation'
  WHEN 'IC-144' THEN 'Deuil normal et pathologique'
  WHEN 'IC-145' THEN 'Surveillance des maladies infectieuses transmissibles'
  WHEN 'IC-146' THEN 'Vaccinations'
  WHEN 'IC-147' THEN 'Fièvre aiguë chez l''enfant et l''adulte'
  WHEN 'IC-148' THEN 'Infections naso-sinusiennes de l''adulte et de l''enfant'
  WHEN 'IC-149' THEN 'Angines de l''adulte et de l''enfant et rhinopharyngites de l''enfant'
  WHEN 'IC-150' THEN 'Otites infectieuses de l''adulte et de l''enfant'
  WHEN 'IC-151' THEN 'Méningites, méningoencéphalites, abcès cérébral chez l''adulte et l''enfant'
  WHEN 'IC-152' THEN 'Endocardite infectieuse'
  WHEN 'IC-153' THEN 'Surveillance des porteurs de valve et prothèses vasculaires'
  WHEN 'IC-154' THEN 'Infections broncho pulmonaires communautaires de l''adulte et de l''enfant'
  WHEN 'IC-155' THEN 'Infections cutanéo-muqueuses et des phanères, bactériennes et mycosiques de l''adulte et de l''enfant'
  WHEN 'IC-156' THEN 'Infections ostéo articulaires (IOA) de l''enfant et de l''adulte'
  WHEN 'IC-157' THEN 'Septicémie/Bactériémie/Fongémie de l''adulte et de l''enfant'
  WHEN 'IC-158' THEN 'Sepsis et choc septique de l''enfant et de l''adulte'
  WHEN 'IC-159' THEN 'Tuberculose de l''adulte et de l''enfant'
  WHEN 'IC-160' THEN 'Tétanos'
  WHEN 'IC-161' THEN 'Infections urinaires de l''enfant et de l''adulte'
  WHEN 'IC-162' THEN 'Infections sexuellement transmissibles (IST) : gonococcies, chlamydioses, syphilis, papillomavirus humain (HPV), trichomonose'
  WHEN 'IC-163' THEN 'Coqueluche'
  WHEN 'IC-164' THEN 'Exanthèmes fébriles de l''enfant'
  WHEN 'IC-165' THEN 'Oreillons'
  WHEN 'IC-166' THEN 'Grippe'
  WHEN 'IC-167' THEN 'Hépatites virales'
  WHEN 'IC-168' THEN 'Infections à herpès virus du sujet immunocompétent'
  WHEN 'IC-169' THEN 'Infections à VIH'
  WHEN 'IC-170' THEN 'Paludisme'
  WHEN 'IC-171' THEN 'Gale et pédiculose'
  WHEN 'IC-172' THEN 'Parasitoses digestives : giardiose, amoebose, téniasis, ascaridiose, oxyurose, anguillulose, cryptosporidiose.'
  WHEN 'IC-173' THEN 'Zoonoses'
  WHEN 'IC-174' THEN 'Pathologie infectieuse chez les migrants adultes et enfants'
  WHEN 'IC-175' THEN 'Voyage en pays tropical de l''adulte et de l''enfant : conseils avant le départ, pathologies du retour : fièvre, diarrhée, manifestations cutanées'
  WHEN 'IC-176' THEN 'Diarrhées infectieuses de l''adulte et de l''enfant'
  WHEN 'IC-177' THEN 'Prescription et surveillance des anti-infectieux chez l''adulte et l''enfant'
  WHEN 'IC-178' THEN 'Risques émergents, bioterrorisme, maladies hautement transmissibles'
  WHEN 'IC-179' THEN 'Risques sanitaires liés à l''eau et à l''alimentation. Toxi-infections alimentaires'
  WHEN 'IC-180' THEN 'Risques sanitaires liés aux irradiations. Radioprotection'
  WHEN 'IC-181' THEN 'La sécurité sanitaire des produits destinés à l''homme. La veille sanitaire'
  WHEN 'IC-182' THEN 'Environnement professionnel et santé au travail'
  WHEN 'IC-183' THEN 'Organisation de la médecine du travail. Prévention des risques professionnels'
  WHEN 'IC-184' THEN 'Accidents du travail et maladies professionnelles : définitions et enjeux'
  WHEN 'IC-185' THEN 'Réaction inflammatoire : aspects biologiques et cliniques. Conduite à tenir'
  WHEN 'IC-186' THEN 'Hypersensibilités et allergies chez l''enfant et l''adulte : aspects physiopathologiques, épidémiologiques, diagnostiques et principes de traitement'
  WHEN 'IC-187' THEN 'Hypersensibilités et allergies cutanéomuqueuses chez l''enfant et l''adulte. Urticaire, dermatites atopique et de contact, conjonctivite allergique.'
  WHEN 'IC-188' THEN 'Hypersensibilité et allergies respiratoires chez l''enfant et chez l''adulte. Asthme, rhinite'
  WHEN 'IC-189' THEN 'Déficit immunitaire'
  WHEN 'IC-190' THEN 'Fièvre prolongée'
  WHEN 'IC-191' THEN 'Fièvre chez un patient immunodéprimé'
  WHEN 'IC-192' THEN 'Pathologies auto-immunes : aspects épidémiologiques, diagnostiques et principes de traitement'
  WHEN 'IC-193' THEN 'Connaître les principaux types de vascularite systémique, les organes cibles, les outils diagnostiques et les moyens thérapeutiques'
  WHEN 'IC-194' THEN 'Lupus systémique. Syndrome des anti-phospholipides (SAPL)'
  WHEN 'IC-195' THEN 'Artérite à cellules géantes'
  WHEN 'IC-196' THEN 'Polyarthrite rhumatoïde'
  WHEN 'IC-197' THEN 'Spondyloarthrite'
  WHEN 'IC-198' THEN 'Arthropathie microcristalline'
  WHEN 'IC-199' THEN 'Syndrome douloureux régional complexe (ex algodystrophie)'
  WHEN 'IC-200' THEN 'Douleur et épanchement articulaire. Arthrite d''évolution récente'
  WHEN 'IC-201' THEN 'Transplantation d''organes : aspects épidémiologiques et immunologiques ; principes de traitement; complications et pronostic ; aspects éthiques et légaux. Prélèvements d''organes et législation.'
  WHEN 'IC-202' THEN 'Biothérapies et thérapies ciblées'
  WHEN 'IC-203' THEN 'Dyspnée aiguë et chronique'
  WHEN 'IC-204' THEN 'Toux chez l''enfant et chez l''adulte (avec le traitement)'
  WHEN 'IC-205' THEN 'Hémoptysie'
  WHEN 'IC-206' THEN 'Épanchement pleural liquidien'
  WHEN 'IC-207' THEN 'Opacités et masses intra-thoraciques chez l''enfant et chez l''adulte'
  WHEN 'IC-208' THEN 'Insuffisance respiratoire chronique'
  WHEN 'IC-209' THEN 'Bronchopneumopathie chronique obstructive chez l''adulte'
  WHEN 'IC-210' THEN 'Pneumopathie interstitielle diffuse'
  WHEN 'IC-211' THEN 'Sarcoïdose'
  WHEN 'IC-212' THEN 'Hémogramme chez l''adulte et l''enfant : indications et interprétation'
  WHEN 'IC-213' THEN 'Anémie chez l''adulte et l''enfant'
  WHEN 'IC-214' THEN 'Thrombopénie chez l''adulte et l''enfant'
  WHEN 'IC-215' THEN 'Purpuras chez l''adulte et l''enfant'
  WHEN 'IC-216' THEN 'Syndrome hémorragique d''origine hématologique'
  WHEN 'IC-217' THEN 'Syndrome mononucléosique'
  WHEN 'IC-218' THEN 'Éosinophilie'
  WHEN 'IC-219' THEN 'Pathologie du fer chez l''adulte et l''enfant'
  WHEN 'IC-220' THEN 'Adénopathie superficielle de l''adulte et de l''enfant'
  WHEN 'IC-221' THEN 'Athérome : épidémiologie et physiopathologie. Le malade poly-athéromateux'
  WHEN 'IC-222' THEN 'Facteurs de risque cardio-vasculaire et prévention'
  WHEN 'IC-223' THEN 'Dyslipidémies'
  WHEN 'IC-224' THEN 'Hypertension artérielle de l''adulte et de l''enfant'
  WHEN 'IC-225' THEN 'Artériopathie oblitérante de l''aorte, des artères viscérales et des membres inférieurs ; anévrysmes'
  WHEN 'IC-226' THEN 'Thrombose veineuse profonde et embolie pulmonaire'
  WHEN 'IC-227' THEN 'Insuffisance veineuse chronique. Varices'
  WHEN 'IC-228' THEN 'Ulcère de jambe'
  WHEN 'IC-229' THEN 'Surveillance et complications des abords veineux'
  WHEN 'IC-230' THEN 'Douleur thoracique aiguë'
  WHEN 'IC-231' THEN 'Électrocardiogramme : indications et interprétations'
  WHEN 'IC-232' THEN 'Fibrillation atriale'
  WHEN 'IC-233' THEN 'Valvulopathies'
  WHEN 'IC-234' THEN 'Insuffisance cardiaque de l''adulte'
  WHEN 'IC-235' THEN 'Péricardite aiguë'
  WHEN 'IC-236' THEN 'Troubles de la conduction intracardiaque'
  WHEN 'IC-237' THEN 'Palpitations'
  WHEN 'IC-238' THEN 'Souffle cardiaque chez l''enfant'
  WHEN 'IC-239' THEN 'Acrosyndromes (phénomène de Raynaud, érythermalgie, acrocyanose, engelures, ischémie digitale)'
  WHEN 'IC-240' THEN 'Hypoglycémie chez l''adulte et l''enfant'
  WHEN 'IC-241' THEN 'Goitre, nodules thyroïdiens et cancers thyroïdiens'
  WHEN 'IC-242' THEN 'Hyperthyroïdie'
  WHEN 'IC-243' THEN 'Hypothyroïdie'
  WHEN 'IC-244' THEN 'Adénome hypophysaire'
  WHEN 'IC-245' THEN 'Insuffisance surrénale chez l''adulte et l''enfant'
  WHEN 'IC-246' THEN 'Gynécomastie'
  WHEN 'IC-247' THEN 'Diabète sucré de types 1 et 2 de l''enfant et de l''adulte. Complications'
  WHEN 'IC-248' THEN 'Prévention primaire par la nutrition chez l''adulte et chez l''enfant'
  WHEN 'IC-249' THEN 'Modifications thérapeutiques du mode de vie (alimentation et activité physique) chez l''adulte et l''enfant'
  WHEN 'IC-250' THEN 'Dénutrition chez l''adulte et l''enfant'
  WHEN 'IC-251' THEN 'Amaigrissement à tous les âges'
  WHEN 'IC-252' THEN 'Troubles nutritionnels chez le sujet âgé'
  WHEN 'IC-253' THEN 'Obésité de l''enfant et de l''adulte'
  WHEN 'IC-254' THEN 'Besoins nutritionnels et grossesse'
  WHEN 'IC-255' THEN 'Diabète gestationnel'
  WHEN 'IC-256' THEN 'Aptitude au sport chez l''adulte et l''enfant ; besoins nutritionnels chez le sportif'
  WHEN 'IC-257' THEN 'Œdèmes des membres inférieurs localisés ou généralisés'
  WHEN 'IC-258' THEN 'Élévation de la créatininémie'
  WHEN 'IC-259' THEN 'Protéinurie et syndrome néphrotique de chez l''l''adulte et de l''enfant'
  WHEN 'IC-260' THEN 'Hématurie'
  WHEN 'IC-261' THEN 'Néphropathie glomérulaire'
  WHEN 'IC-262' THEN 'Néphropathies interstitielles'
  WHEN 'IC-263' THEN 'Néphropathies vasculaires'
  WHEN 'IC-264' THEN 'Insuffisance rénale chronique chez l''adulte et l''enfant'
  WHEN 'IC-265' THEN 'Lithiase urinaire'
  WHEN 'IC-266' THEN 'Polykystose rénale'
  WHEN 'IC-267' THEN 'Troubles de l''équilibre acido-basique et désordres hydro-électrolytiques'
  WHEN 'IC-268' THEN 'Hypercalcémie'
  WHEN 'IC-269' THEN 'Douleurs abdominales aiguës chez l''enfant et chez l''adulte'
  WHEN 'IC-270' THEN 'Douleurs lombaires aiguës chez l''enfant et chez l''adulte'
  WHEN 'IC-271' THEN 'Reflux gastro-œsophagien chez le nourrisson, chez l''enfant et chez l''adulte. Hernie hiatale'
  WHEN 'IC-272' THEN 'Ulcère gastrique et duodénal. Gastrite'
  WHEN 'IC-273' THEN 'Dysphagie'
  WHEN 'IC-274' THEN 'Vomissements du nourrisson, de l''enfant et de l''adulte'
  WHEN 'IC-275' THEN 'Splénomégalie'
  WHEN 'IC-276' THEN 'Hépatomégalie et masse abdominale'
  WHEN 'IC-277' THEN 'Lithiase biliaire et complications'
  WHEN 'IC-278' THEN 'Ictère'
  WHEN 'IC-279' THEN 'Cirrhose et complications'
  WHEN 'IC-280' THEN 'Ascite'
  WHEN 'IC-281' THEN 'Pancréatite chronique'
  WHEN 'IC-282' THEN 'Maladies Inflammatoires Chroniques de l''Intestin (MICI) chez l''adulte'
  WHEN 'IC-283' THEN 'Constipation chez l''enfant et l''adulte (avec le traitement)'
  WHEN 'IC-284' THEN 'Colopathie fonctionnelle'
  WHEN 'IC-285' THEN 'Diarrhée chronique chez l''adulte et l''enfant'
  WHEN 'IC-286' THEN 'Diarrhée aiguë et déshydratation chez le nourrisson, l''enfant et l''adulte'
  WHEN 'IC-287' THEN 'Diverticulose colique et diverticulite aiguë du sigmoïde'
  WHEN 'IC-288' THEN 'Pathologie hémorroïdaire'
  WHEN 'IC-289' THEN 'Hernie pariétale chez l''enfant et l''adulte'
  WHEN 'IC-290' THEN 'Épidémiologie, facteurs de risque, prévention et dépistage des cancers'
  WHEN 'IC-291' THEN 'Cancer : cancérogénèse, oncogénétique'
  WHEN 'IC-292' THEN 'Diagnostic des cancers : signes d''appel et investigations para-cliniques ; caractérisation du stade ; pronostic'
  WHEN 'IC-293' THEN 'Le médecin préleveur de cellules et/ou de tissus pour des examens d''Anatomie et Cytologie Pathologiques : connaître les principes de réalisation, transmission et utilisation des prélèvements à visée sanitaire et de recherche'
  WHEN 'IC-294' THEN 'Traitement des cancers : principales modalités, classes thérapeutiques et leurs complications majeures. La décision thérapeutique pluridisciplinaire et l''information du malade'
  WHEN 'IC-295' THEN 'Prise en charge et accompagnement d''un malade atteint de cancer à tous les stades de la maladie dont le stade de soins palliatifs en abordant les problématiques techniques, relationnelles, sociales et éthiques. Traitements symptomatiques. Modalités de surveillance.'
  WHEN 'IC-296' THEN 'Agranulocytose médicamenteuse : conduite à tenir'
  WHEN 'IC-297' THEN 'Cancer de l''enfant : particularités épidémiologiques, diagnostiques et thérapeutiques'
  WHEN 'IC-298' THEN 'Tumeurs de la cavité buccale, naso-sinusiennes et du cavum, et des voies aérodigestives supérieures.'
  WHEN 'IC-299' THEN 'Tumeurs intracrâniennes'
  WHEN 'IC-300' THEN 'Tumeurs du col utérin, tumeur du corps utérin'
  WHEN 'IC-301' THEN 'Tumeurs du colon et du rectum'
  WHEN 'IC-302' THEN 'Tumeurs cutanées, épithéliales et mélaniques'
  WHEN 'IC-303' THEN 'Tumeurs de l''estomac'
  WHEN 'IC-304' THEN 'Tumeurs du foie, primitives et secondaires'
  WHEN 'IC-305' THEN 'Tumeurs de l''œsophage'
  WHEN 'IC-306' THEN 'Tumeurs de l''ovaire'
  WHEN 'IC-307' THEN 'Tumeurs des os primitives et secondaires'
  WHEN 'IC-308' THEN 'Tumeurs du pancréas'
  WHEN 'IC-309' THEN 'Tumeurs du poumon, primitives et secondaires'
  WHEN 'IC-310' THEN 'Tumeurs de la prostate'
  WHEN 'IC-311' THEN 'Tumeurs du rein de l''adulte'
  WHEN 'IC-312' THEN 'Tumeurs du sein'
  WHEN 'IC-313' THEN 'Tumeurs du testicule'
  WHEN 'IC-314' THEN 'Tumeurs vésicales'
  WHEN 'IC-315' THEN 'Leucémies aiguës'
  WHEN 'IC-316' THEN 'Syndromes myélodysplasiques'
  WHEN 'IC-317' THEN 'Syndromes myéloprolifératifs'
  WHEN 'IC-318' THEN 'Leucémies lymphoïdes chroniques'
  WHEN 'IC-319' THEN 'Lymphomes malins'
  WHEN 'IC-320' THEN 'Myélome multiple des os'
  WHEN 'IC-321' THEN 'Principe du bon usage du médicament'
  WHEN 'IC-322' THEN 'La décision thérapeutique personnalisée : bon usage dans des situations à risque'
  WHEN 'IC-323' THEN 'Analyser et utiliser les résultats des études cliniques dans la perspective du bon usage - analyse critique, recherche clinique et niveaux de preuve.'
  WHEN 'IC-324' THEN 'Éducation thérapeutique, observance et automédication'
  WHEN 'IC-325' THEN 'Identification et gestion des risques liés aux médicaments et aux biomatériaux, risque iatrogène, erreur médicamenteuse'
  WHEN 'IC-326' THEN 'Cadre réglementaire de la prescription thérapeutique et recommandations pour le bon usage'
  WHEN 'IC-327' THEN 'Principes de la médecine intégrative, utilité et risques des interventions non médicamenteuses et des thérapies complémentaires'
  WHEN 'IC-328' THEN 'Thérapeutiques non médicamenteuses et dispositifs médicaux'
  WHEN 'IC-329' THEN 'Transfusion sanguine et produits dérivés du sang : indications, complications. Hémovigilance'
  WHEN 'IC-330' THEN 'Prescription et surveillance des classes de médicaments les plus courantes chez l''adulte et chez l''enfant, hors anti-infectieux. Connaitre les grands principes thérapeutiques.'
  WHEN 'IC-331' THEN 'Arrêt cardio-circulatoire'
  WHEN 'IC-332' THEN 'État de choc. Principales étiologies : hypovolémique, septique, cardiogénique, anaphylactique'
  WHEN 'IC-333' THEN 'Situations sanitaires exceptionnelles'
  WHEN 'IC-334' THEN 'Prise en charge immédiate pré-hospitalière et à l''arrivée à l''hôpital, évaluation des complications chez : un brûlé, un traumatisé sévère, un traumatisé thoracique, un traumatisé abdominal, un traumatisé des membres et/ou du bassin, un traumatisé du rachis ou vertébro-médullaire, un traumatisé crânien ou crânio-encéphalique'
  WHEN 'IC-335' THEN 'Orientation diagnostique et conduite à tenir devant un traumatisme maxillo-facial et oculaire'
  WHEN 'IC-336' THEN 'Coma non traumatique chez l''adulte et chez l''enfant'
  WHEN 'IC-337' THEN 'Principales intoxications aiguës'
  WHEN 'IC-338' THEN 'Œdème de Quincke et anaphylaxie'
  WHEN 'IC-339' THEN 'Syndromes coronariens aigus'
  WHEN 'IC-340' THEN 'Accidents vasculaires cérébraux'
  WHEN 'IC-341' THEN 'Hémorragie méningée'
  WHEN 'IC-342' THEN 'Malaise, perte de connaissance, crise convulsive chez l''adulte'
  WHEN 'IC-343' THEN 'État confusionnel et trouble de conscience chez l''adulte et chez l''enfant'
  WHEN 'IC-344' THEN 'Prise en charge d''une patiente atteinte de pré-éclampsie'
  WHEN 'IC-345' THEN 'Malaise grave du nourrisson et mort inattendue du nourrisson'
  WHEN 'IC-346' THEN 'Convulsions chez le nourrisson et chez l''enfant'
  WHEN 'IC-347' THEN 'Rétention aiguë d''urine'
  WHEN 'IC-348' THEN 'Insuffisance rénale aiguë - Anurie'
  WHEN 'IC-349' THEN 'Infection aiguë des parties molles (abcès, panaris, phlegmon des gaines)'
  WHEN 'IC-350' THEN 'Grosse jambe rouge aiguë'
  WHEN 'IC-351' THEN 'Agitation et délire aiguë'
  WHEN 'IC-352' THEN 'Crise d''angoisse aiguë et attaque de panique'
  WHEN 'IC-353' THEN 'Risque et conduite suicidaires chez l''enfant, l''adolescent et l''adulte : identification et prise en charge'
  WHEN 'IC-354' THEN 'Syndrome occlusif de l''enfant et de l''adulte'
  WHEN 'IC-355' THEN 'Hémorragie digestive'
  WHEN 'IC-356' THEN 'Appendicite de l''enfant et de l''adulte'
  WHEN 'IC-357' THEN 'Péritonite aiguë chez l''enfant et chez l''adulte'
  WHEN 'IC-358' THEN 'Pancréatite aiguë'
  WHEN 'IC-359' THEN 'Détresse et insuffisance respiratoire aigüe du nourrisson, de l''enfant et de l''adulte'
  WHEN 'IC-360' THEN 'Pneumothorax'
  WHEN 'IC-361' THEN 'Lésions péri-articulaires et ligamentaires du genou, de la cheville et de l''épaule'
  WHEN 'IC-362' THEN 'Prothèses et ostéosynthèses'
  WHEN 'IC-363' THEN 'Fractures fréquentes de l''adulte et du sujet âgé'
  WHEN 'IC-364' THEN 'Fractures chez l''enfant : particularités épidémiologiques, diagnostiques et thérapeutiques'
  WHEN 'IC-365' THEN 'Surveillance d''un malade sous plâtre/résine, diagnostiquer une complication'
  WHEN 'IC-366' THEN 'Exposition accidentelle aux liquides biologiques : conduite à tenir'
  WHEN 'IC-367' THEN 'Impact de l''environnement sur la santé.'
  ELSE title
END,
updated_at = now()
WHERE item_code ~ '^IC-[0-9]+$';