-- ---------------------------------------------------------------------------
-- Titres officiels des 367 items EDN
--
-- Source : livret.uness.fr/lisa/2026, page « Item de connaissance 2C »,
-- lue le 18/09/2026 avec la session de la proprietaire.
--
-- Constat sur edn_items_complete : 367 / 367 items presents, aucun code mal
-- forme, aucun slug en double. Mais 27 titres designent AUTRE CHOSE que
-- l'item officiel, et 30 sont tronques.
-- Exemples : l'item 2 s'appelait « Les droits du patient » alors que l'item 2
-- du referentiel est « Les valeurs professionnelles du medecin et des autres
-- professions de sante » ; l'item 5 s'appelait « La gestion des erreurs et
-- des plaintes » au lieu de « Responsabilites medicale penale, civile,
-- administrative et disciplinaire ».
-- Les competences, elles, etaient rattachees au bon numero d'item (verifie :
-- 4872 / 4872 item_parent corrects). C'est donc bien le titre qui etait faux,
-- pas le rattachement : un etudiant lisait le bon contenu sous le mauvais nom.
--
-- Cette migration ne touche que la colonne title. Aucune suppression.
-- ---------------------------------------------------------------------------

BEGIN;

CREATE TABLE IF NOT EXISTS edn_items_titres_avant_uness_20260918 AS
  SELECT item_code, title FROM public.edn_items_complete;

CREATE TEMP TABLE uness_items (item_code text PRIMARY KEY, title text NOT NULL)
  ON COMMIT DROP;

INSERT INTO uness_items (item_code, title) VALUES
('IC-1','La relation médecin-malade dans le cadre du colloque singulier ou au sein d''une équipe, le cas échéant pluriprofessionnelle. La communication avec le patient et son entourage. L''annonce d''une maladie grave ou létale ou d''un dommage associé aux soins. La formation du patient. La personnalisation de la prise en charge médicale'),
('IC-2','Les valeurs professionnelles du médecin et des autres professions de santé'),
('IC-3','Le raisonnement et la décision en médecine. La médecine fondée sur les preuves (Evidence Based Medicine, EBM). La décision médicale partagée. La controverse'),
('IC-4','Qualité et sécurité des soins. La sécurité du patient. La gestion des risques. Les événements indésirables associés aux soins (EIAS). Démarche qualité et évaluation des pratiques professionnelles'),
('IC-5','Responsabilités médicale pénale, civile, administrative et disciplinaire. La gestion des erreurs et des plaintes ; l''aléa thérapeutique'),
('IC-6','L''organisation de l''exercice clinique et les méthodes qui permettent de sécuriser le parcours du patient'),
('IC-7','Les droits individuels et collectifs du patient'),
('IC-8','Les discriminations'),
('IC-9','Introduction à l''éthique médicale'),
('IC-10','Approches transversales du corps'),
('IC-11','Violences et santé'),
('IC-12','Violences sexuelles'),
('IC-13','Certificats médicaux. Décès et législation'),
('IC-14','La mort'),
('IC-15','Soins psychiatriques sans consentement'),
('IC-16','Organisation du système de soins. Sa régulation. Les indicateurs. Parcours de soins'),
('IC-17','Télémédecine, télésanté et téléservices en santé'),
('IC-18','Santé et numérique'),
('IC-19','La sécurité sociale. L''assurance maladie. Les assurances complémentaires. La complémentaire santé solidaire (CSS). La consommation médicale. Protection sociale. Consommation médicale et économie de la santé'),
('IC-20','La méthodologie de la recherche en santé'),
('IC-21','Mesure de l''état de santé de la population'),
('IC-22','Maladies rares'),
('IC-23','Grossesse normale'),
('IC-24','Principales complications de la grossesse'),
('IC-25','Grossesse extra-utérine'),
('IC-26','Douleur abdominale aiguë chez une femme enceinte'),
('IC-27','Prévention des risques fœtaux : infection, médicaments, toxiques, irradiation'),
('IC-28','Connaître les particularités de l''infection urinaire au cours de la grossesse'),
('IC-29','Connaître les principaux risques professionnels pour la maternité, liés au travail de la mère'),
('IC-30','Prématurité et retard de croissance intra-utérin : facteurs de risque et prévention'),
('IC-31','Accouchement, délivrance et suites de couches normales'),
('IC-32','Évaluation et soins du nouveau-né à terme'),
('IC-33','Allaitement maternel'),
('IC-34','Suites de couches pathologiques : pathologie maternelle dans les 40 jours'),
('IC-35','Anomalies du cycle menstruel. Métrorragies'),
('IC-36','Contraception. (voir item 330)'),
('IC-37','Interruption volontaire de grossesse'),
('IC-38','Infertilité du couple : conduite de la première consultation'),
('IC-39','Assistance médicale à la procréation : principaux aspects biologiques, médicaux et éthiques'),
('IC-40','Algies pelviennes chez la femme'),
('IC-41','Endométriose'),
('IC-42','Aménorrhée'),
('IC-43','Hémorragie génitale chez la femme'),
('IC-44','Tuméfaction pelvienne chez la femme'),
('IC-45','Spécificités des maladies génétiques. (voir item 9)'),
('IC-46','Médecine génomique'),
('IC-47','Suivi d''un nourrisson, d''un enfant et d''un adolescent normal. Dépistage des anomalies orthopédiques, des troubles visuels, auditifs et dentaires. Examens de santé obligatoires. Médecine scolaire. Mortalité et morbidité infantiles'),
('IC-48','Alimentation et besoins nutritionnels du nourrisson et de l''enfant'),
('IC-49','Puberté normale et pathologique'),
('IC-50','Pathologie génito-scrotale chez le garçon et chez l''homme'),
('IC-51','Troubles de la miction chez l''enfant'),
('IC-52','Strabisme et amblyopie de l''enfant'),
('IC-53','Retard de croissance staturo-pondérale'),
('IC-54','Boiterie chez l''enfant'),
('IC-55','Développement psychomoteur du nourrisson et de l''enfant : aspects normaux et pathologiques (sommeil, alimentation, contrôles sphinctériens, psychomotricité, langage, intelligence). L''installation précoce de la relation parents-enfant et son importance. Troubles de l''apprentissage (voir item 122)'),
('IC-56','L''enfant handicapé : orientation et prise en charge (voir items 118, 121)'),
('IC-57','Maltraitance et enfants en danger. Protection maternelle et infantile'),
('IC-58','Sexualité normale et ses troubles'),
('IC-59','Sujets en situation de précarité'),
('IC-60','Connaître les facteurs de risque, prévention, dépistage des troubles psychiques de l''enfant à la personne âgée'),
('IC-61','Connaître les bases des classifications des troubles mentaux de l''enfant à la personne âgée'),
('IC-62','Décrire l''organisation de l''offre de soins en psychiatrie, de l''enfant à la personne âgée'),
('IC-63','Troubles schizophréniques de l''adolescent et de l''adulte'),
('IC-64','Troubles bipolaires de l''adolescent et de l''adulte'),
('IC-65','Trouble délirant persistant'),
('IC-66','Diagnostiquer : un trouble dépressif, un trouble anxieux, un trouble obsessionnel compulsif, un trouble de stress post-traumatique, un trouble de l''adaptation, un trouble de la personnalité'),
('IC-67','Troubles du neurodéveloppement (voir items 55, 118, 121, 122, 138)'),
('IC-68','Troubles du comportement de l''enfant et de l''adolescent'),
('IC-69','Troubles psychiques de la grossesse et du post-partum'),
('IC-70','Troubles psychiques du sujet âgé'),
('IC-71','Troubles des conduites alimentaires chez l''adolescent et l''adulte (voir item 253)'),
('IC-72','Troubles à symptomatologie somatique et apparentés à tous les âges'),
('IC-73','Différents types de techniques psychothérapeutiques'),
('IC-74','Prescription et surveillance des psychotropes (voir item 330)'),
('IC-75','Addiction au tabac'),
('IC-76','Addiction à l''alcool'),
('IC-77','Addiction aux médicaments psychotropes (benzodiazépines et apparentés). (voir item 322)'),
('IC-78','Addiction au cannabis, à la cocaïne, aux amphétamines, aux opiacés, aux drogues de synthèse. (voir item 322)'),
('IC-79','Addictions comportementales'),
('IC-80','Dopage et conduites dopantes. (voir item 256)'),
('IC-81','Altération chronique de la vision'),
('IC-82','Altération aiguë de la vision'),
('IC-83','Infections et inflammations oculaires'),
('IC-84','Glaucomes'),
('IC-85','Troubles de la réfraction'),
('IC-86','Pathologie des paupières'),
('IC-87','Epistaxis'),
('IC-88','Trouble aigu de la parole. Dysphonie'),
('IC-89','Altération de la fonction auditive'),
('IC-90','Pathologie des glandes salivaires'),
('IC-91','Déficit neurologique récent. (voir item 340)'),
('IC-92','Déficit moteur et/ou sensitif des membres'),
('IC-93','Compression médullaire non traumatique et syndrome de la queue de cheval'),
('IC-94','Rachialgie'),
('IC-95','Radiculalgie et syndrome canalaire'),
('IC-96','Neuropathies périphériques'),
('IC-97','Polyradiculonévrite aiguë inflammatoire (syndrome de Guillain-Barré)'),
('IC-98','Myasthénie'),
('IC-99','Migraine, névralgie du trijumeau et algies de la face'),
('IC-100','Céphalée inhabituelle aiguë et chronique chez l''adulte et l''enfant'),
('IC-101','Paralysie faciale'),
('IC-102','Diplopie'),
('IC-103','Vertige'),
('IC-104','Sclérose en plaques'),
('IC-105','Épilepsie de l''enfant et de l''adulte'),
('IC-106','Maladie de Parkinson'),
('IC-107','Mouvements anormaux'),
('IC-108','Confusion, démences. (voir item 132)'),
('IC-109','Troubles de la marche et de l''équilibre'),
('IC-110','Troubles du sommeil de l''enfant et de l''adulte'),
('IC-111','Dermatoses faciales : acné, rosacée, dermatite séborrhéique'),
('IC-112','Dermatose bulleuse touchant la peau et/ou les muqueuses externes'),
('IC-113','Hémangiomes et malformations vasculaires cutanées'),
('IC-114','Exanthème et érythrodermie de l''adulte et de l''enfant. (voir item 164)'),
('IC-115','Toxidermies'),
('IC-116','Prurit'),
('IC-117','Psoriasis'),
('IC-118','La personne handicapée : bases de l''évaluation fonctionnelle et thérapeutique. (voir item 56)'),
('IC-119','Soins et accompagnement dans la maladie chronique et le handicap'),
('IC-120','Complications de l''immobilité et du décubitus. Prévention et prise en charge'),
('IC-121','Le handicap psychique. (voir item 56 et 118)'),
('IC-122','Principales techniques de rééducation et de réadaptation. (voir item 55)'),
('IC-123','Vieillissement normal : aspects biologiques, fonctionnels et relationnels. Données épidémiologiques et sociologiques. Prévention du vieillissement pathologique'),
('IC-124','Ménopause, insuffisance ovarienne prématurée, andropause, déficit androgénique lié à l''âge. (Voir item 330)'),
('IC-125','Troubles de la miction et incontinence urinaire de l''adulte et du sujet âgé'),
('IC-126','Trouble de l''érection'),
('IC-127','Hypertrophie bénigne de la prostate'),
('IC-128','Ostéopathies fragilisantes'),
('IC-129','Arthrose'),
('IC-130','La personne âgée malade : particularités sémiologiques, psychologiques et thérapeutiques. (voir item 322)'),
('IC-131','Troubles de la marche et de l''équilibre. (voir item 109)'),
('IC-132','Troubles cognitifs du sujet âgé. (voir item 108)'),
('IC-133','Autonomie et dépendance chez le sujet âgé'),
('IC-134','Bases neurophysiologiques, mécanismes physiopathologiques d''une douleur aiguë et d''une douleur chronique'),
('IC-135','Thérapeutiques antalgiques, médicamenteuses et non médicamenteuses. (voir item 330)'),
('IC-136','Anesthésie locale, locorégionale et générale'),
('IC-137','Douleur chez l''enfant : évaluation et traitements antalgique'),
('IC-138','Douleur chez la personne vulnérable'),
('IC-139','Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (1). Principaux repères cliniques. Modalités d''organisation des équipes, en établissement de santé et en et en ambulatoire'),
('IC-140','Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (2). Accompagnement de la personne malade et de son entourage. Principaux repères éthiques'),
('IC-141','Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (3). La sédation pour détresse en phase terminale et dans des situations spécifiques et complexes en fin de vie. Réponse à la demande d''euthanasie ou de suicide assisté'),
('IC-142','Connaître les aspects spécifiques des soins palliatifs en pédiatrie'),
('IC-143','Connaître les aspects spécifiques des soins palliatifs en réanimation'),
('IC-144','Deuil normal et pathologique'),
('IC-145','Surveillance des maladies infectieuses transmissibles'),
('IC-146','Vaccinations'),
('IC-147','Fièvre aiguë chez l''enfant et l''adulte'),
('IC-148','Infections naso-sinusiennes de l''adulte et de l''enfant'),
('IC-149','Angines de l''adulte et de l''enfant'),
('IC-150','Otites infectieuses de l''adulte et de l''enfant'),
('IC-151','Méningites, méningoencéphalites, abcès cérébral chez l''adulte et l''enfant'),
('IC-152','Endocardite infectieuse'),
('IC-153','Surveillance des porteurs de prothèses valvulaires'),
('IC-154','Infections broncho pulmonaires communautaires de l''adulte et de l''enfant'),
('IC-155','Infections cutanéo-muqueuses et des phanères, bactériennes et mycosiques de l''adulte et de l''enfant'),
('IC-156','Infections ostéo articulaires (IOA) de l''enfant et de l''adulte'),
('IC-157','Bactériémie/Fongémie de l''adulte et de l''enfant'),
('IC-158','Sepsis et choc septique de l''enfant et de l''adulte'),
('IC-159','Tuberculose de l''adulte et de l''enfant'),
('IC-160','Tétanos'),
('IC-161','Infections urinaires de l''enfant et de l''adulte'),
('IC-162','Infections sexuellement transmissibles (IST) : gonococcies, chlamydioses, syphilis, papillomavirus humain (HPV), trichomonose'),
('IC-163','Coqueluche'),
('IC-164','Exanthèmes fébriles de l''enfant'),
('IC-165','Oreillons'),
('IC-166','Grippe'),
('IC-167','Hépatites virales'),
('IC-168','Infections à herpès virus du sujet immunocompétent'),
('IC-169','Infections à VIH'),
('IC-170','Paludisme'),
('IC-171','Gale et pédiculose'),
('IC-172','Parasitoses digestives : giardiose, amoebose, téniasis, ascaridiose, oxyurose, anguillulose, cryptosporidiose'),
('IC-173','Zoonoses'),
('IC-174','Pathologie infectieuse chez les migrants adultes et enfants'),
('IC-175','Voyage en pays tropical de l''adulte et de l''enfant : conseils avant le départ, pathologies du retour : fièvre, diarrhée, manifestations cutanées'),
('IC-176','Diarrhées infectieuses de l''adulte et de l''enfant'),
('IC-177','Prescription et surveillance des anti-infectieux chez l''adulte et l''enfant (voir item 330)'),
('IC-178','Risques émergents, bioterrorisme, maladies hautement transmissibles'),
('IC-179','Risques sanitaires liés à l''eau et à l''alimentation. Toxi-infections alimentaires'),
('IC-180','Risques sanitaires liés aux irradiations. Radioprotection'),
('IC-181','La sécurité sanitaire des produits destinés à l''homme. La veille sanitaire (voir item 325)'),
('IC-182','Environnement professionnel et santé au travail'),
('IC-183','Organisation de la médecine du travail. Prévention des risques professionnels'),
('IC-184','Accidents du travail et maladies professionnelles : définition et enjeux'),
('IC-185','Réaction inflammatoire : aspects biologiques et cliniques. Conduite à tenir'),
('IC-186','Hypersensibilités et allergies chez l''enfant et l''adulte : aspects physiopathologiques, épidémiologiques, diagnostiques et principes de traitement'),
('IC-187','Hypersensibilités et allergies cutanéomuqueuses chez l''enfant et l''adulte. Urticaire, dermatites atopique et de contact'),
('IC-188','Hypersensibilité et allergies respiratoires chez l''enfant et chez l''adulte. Asthme, rhinite'),
('IC-189','Déficit immunitaire'),
('IC-190','Fièvre prolongée'),
('IC-191','Fièvre chez un patient immunodéprimé'),
('IC-192','Pathologies auto-immunes : aspects épidémiologiques, diagnostiques et principes de traitement'),
('IC-193','Connaître les principaux types de vascularite systémique, les organes cibles, les outils diagnostiques et les moyens thérapeutiques'),
('IC-194','Lupus systémique (LS). Syndrome des anti-phospholipides (SAPL)'),
('IC-195','Artérite à cellules géantes'),
('IC-196','Polyarthrite rhumatoïde'),
('IC-197','Spondyloarthrite'),
('IC-198','Arthropathies microcristallines'),
('IC-199','Syndrome douloureux régional complexe (ex algodystrophie)'),
('IC-200','Douleur et épanchement articulaire. Arthrite d''évolution récente'),
('IC-201','Transplantation d''organes : aspects épidémiologiques et immunologiques ; principes de traitement et surveillance ; complications et pronostic ; aspects éthiques et légaux. Prélèvements d''organes et législation'),
('IC-202','Biothérapies et thérapies ciblées'),
('IC-203','Dyspnée aiguë et chronique'),
('IC-204','Toux chez l''enfant et chez l''adulte (avec le traitement)'),
('IC-205','Hémoptysie'),
('IC-206','Épanchement pleural liquidien'),
('IC-207','Opacités et masses intra-thoraciques chez l''enfant et chez l''adulte'),
('IC-208','Insuffisance respiratoire chronique'),
('IC-209','Bronchopneumopathie chronique obstructive chez l''adulte'),
('IC-210','Pneumopathie interstitielle diffuse'),
('IC-211','Sarcoïdose'),
('IC-212','Hémogramme chez l''adulte et l''enfant : indications et interprétation'),
('IC-213','Anémie chez l''adulte et l''enfant'),
('IC-214','Thrombopénie chez l''adulte et l''enfant'),
('IC-215','Purpuras chez l''adulte et l''enfant'),
('IC-216','Syndrome hémorragique d''origine hématologique'),
('IC-217','Syndrome mononucléosique'),
('IC-218','Éosinophilie'),
('IC-219','Pathologie du fer chez l''adulte et l''enfant'),
('IC-220','Adénopathie superficielle de l''adulte et de l''enfant'),
('IC-221','Athérome : épidémiologie et physiopathologie. Le malade poly-athéromateux'),
('IC-222','Facteurs de risque cardio-vasculaire et prévention'),
('IC-223','Dyslipidémies'),
('IC-224','Hypertension artérielle de l''adulte et de l''enfant'),
('IC-225','Artériopathie de l''aorte, des artères viscérales et des membres inférieurs ; anévrysmes'),
('IC-226','Thrombose veineuse profonde et embolie pulmonaire (voir item 330)'),
('IC-227','Insuffisance veineuse chronique. Varices'),
('IC-228','Ulcère de jambe'),
('IC-229','Surveillance et complications des abords veineux'),
('IC-230','Douleur thoracique aiguë'),
('IC-231','Électrocardiogramme : indications et interprétations'),
('IC-232','Fibrillation atriale'),
('IC-233','Valvulopathies'),
('IC-234','Insuffisance cardiaque de l''adulte'),
('IC-235','Péricardite aiguë'),
('IC-236','Troubles de la conduction intracardiaque'),
('IC-237','Palpitations'),
('IC-238','Souffle cardiaque chez l''enfant'),
('IC-239','Acrosyndromes (phénomène de Raynaud, érythermalgie, acrocyanose, engelures, ischémie digitale)'),
('IC-240','Hypoglycémie chez l''adulte et l''enfant'),
('IC-241','Goitre, nodules thyroïdiens et cancers thyroïdiens'),
('IC-242','Hyperthyroïdie'),
('IC-243','Hypothyroïdie'),
('IC-244','Adénome hypophysaire'),
('IC-245','Insuffisance surrénale chez l''adulte et l''enfant'),
('IC-246','Gynécomastie'),
('IC-247','Diabète sucré de type 1 et 2 de l''enfant et de l''adulte. Complications'),
('IC-248','Prévention primaire par la nutrition chez l''adulte et l''enfant'),
('IC-249','Modifications thérapeutiques du mode de vie (alimentation et activité physique) chez l''adulte et l''enfant'),
('IC-250','Dénutrition chez l''adulte et l''enfant'),
('IC-251','Amaigrissement à tous les âges'),
('IC-252','Troubles nutritionnels chez le sujet âgé'),
('IC-253','Obésité de l''enfant et de l''adulte (voir item 71)'),
('IC-254','Besoins nutritionnels de la femme enceinte'),
('IC-255','Diabète gestationnel'),
('IC-256','Aptitude au sport chez l''adulte et l''enfant ; besoins nutritionnels chez le sportif (voir item 80)'),
('IC-257','Œdèmes des membres inférieurs localisés ou généralisés'),
('IC-258','Élévation de la créatininémie'),
('IC-259','Protéinurie et syndrome néphrotique chez l''adulte et de l''enfant'),
('IC-260','Hématurie'),
('IC-261','Néphropathie glomérulaire'),
('IC-262','Néphropathies interstitielles'),
('IC-263','Néphropathies vasculaires'),
('IC-264','Insuffisance rénale chronique chez l''adulte et l''enfant'),
('IC-265','Lithiase urinaire'),
('IC-266','Polykystose rénale'),
('IC-267','Troubles de l''équilibre acido-basique et désordres hydro-électrolytiques'),
('IC-268','Hypercalcémie'),
('IC-269','Douleurs abdominales aiguës chez l''enfant et chez l''adulte'),
('IC-270','Douleurs lombaires aiguës'),
('IC-271','Reflux gastro-œsophagien chez le nourrisson, chez l''enfant et chez l''adulte. Hernie hiatale'),
('IC-272','Ulcère gastrique et duodénal. Gastrite'),
('IC-273','Dysphagie'),
('IC-274','Vomissements du nourrisson, de l''enfant et de l''adulte'),
('IC-275','Splénomégalie'),
('IC-276','Hépatomégalie et masse abdominale'),
('IC-277','Lithiase biliaire et complications'),
('IC-278','Ictère de l''adulte et de l''enfant'),
('IC-279','Cirrhose et complications'),
('IC-280','Ascite'),
('IC-281','Pancréatite chronique'),
('IC-282','Maladies inflammatoires chroniques de l''intestin (MICI) chez l''adulte'),
('IC-283','Constipation chez l''enfant et l''adulte'),
('IC-284','Colopathie fonctionnelle'),
('IC-285','Diarrhée chronique chez l''adulte et l''enfant'),
('IC-286','Diarrhée aiguë et déshydratation chez le nourrisson, l''enfant et l''adulte'),
('IC-287','Diverticulose colique et diverticulite aiguë du sigmoïde'),
('IC-288','Pathologie hémorroïdaire'),
('IC-289','Hernie pariétale chez l''enfant et l''adulte'),
('IC-290','Épidémiologie, facteurs de risque, prévention et dépistage des cancers'),
('IC-291','Cancer : cancérogénèse, oncogénétique'),
('IC-292','Diagnostic des cancers : signes d''appel et investigations para-cliniques ; caractérisation du stade ; pronostic'),
('IC-293','Le médecin préleveur de cellules et/ou de tissus pour des examens d''Anatomie et Cytologie Pathologiques : connaître les principes de réalisation, transmission et utilisation des prélèvements à visée sanitaire et de recherche'),
('IC-294','Traitement des cancers : principales modalités, classes thérapeutiques et leurs complications majeures. La décision thérapeutique pluridisciplinaire et l''information du malade'),
('IC-295','Prise en charge et accompagnement d''un malade atteint de cancer à tous les stades de la maladie dont le stade de soins palliatifs en abordant les problématiques techniques, relationnelles, sociales et éthiques'),
('IC-296','Agranulocytose médicamenteuse : conduite à tenir'),
('IC-297','Cancer de l''enfant : particularités épidémiologiques, diagnostiques et thérapeutiques'),
('IC-298','Tumeurs de la cavité buccale, naso-sinusiennes et du cavum, et des voies aérodigestives supérieures'),
('IC-299','Tumeurs intracrâniennes'),
('IC-300','Tumeurs du col utérin, tumeur du corps utérin'),
('IC-301','Tumeurs du colon et du rectum'),
('IC-302','Tumeurs cutanées, épithéliales et mélaniques'),
('IC-303','Tumeurs de l''estomac'),
('IC-304','Tumeurs du foie, primitives et secondaires'),
('IC-305','Tumeurs de l''œsophage'),
('IC-306','Tumeurs de l''ovaire'),
('IC-307','Tumeurs des os primitives et secondaires'),
('IC-308','Tumeurs du pancréas'),
('IC-309','Tumeurs du poumon, primitives et secondaires'),
('IC-310','Tumeurs de la prostate'),
('IC-311','Tumeurs du rein de l''adulte'),
('IC-312','Tumeurs du sein'),
('IC-313','Tumeurs du testicule'),
('IC-314','Tumeurs vésicales'),
('IC-315','Leucémies aiguës'),
('IC-316','Syndromes myélodysplasiques'),
('IC-317','Syndromes myéloprolifératifs'),
('IC-318','Leucémies lymphoïdes chroniques'),
('IC-319','Lymphomes malins'),
('IC-320','Myélome multiple des os'),
('IC-321','Principe du bon usage du médicament et des thérapeutiques non médicamenteuses'),
('IC-322','La décision thérapeutique personnalisée : bon usage dans des situations à risque'),
('IC-323','Analyser et utiliser les résultats des études cliniques dans la perspective du bon usage - analyse critique, recherche clinique et niveaux de preuve (voir item 3)'),
('IC-324','Éducation thérapeutique, observance et automédication'),
('IC-325','Identification et gestion des risques liés aux médicaments et aux biomatériaux, risque iatrogène, erreur médicamenteuse (voir items 4 et 5)'),
('IC-326','Cadre réglementaire de la prescription thérapeutique et recommandations pour le bon usage'),
('IC-327','Principes de la médecine intégrative, utilité et risques des interventions non médicamenteuses et des thérapies complémentaires'),
('IC-328','Thérapeutiques non médicamenteuses et dispositifs médicaux'),
('IC-329','Connaître les caractéristiques des produits sanguins labiles (PSL) et leur spécificité'),
('IC-330','Prescription et surveillance des classes de médicaments les plus courantes chez l''adulte et chez l''enfant, hors anti-infectieux (voir item 177). Connaître le bon usage des principales classes thérapeutiques'),
('IC-331','Arrêt cardio-circulatoire'),
('IC-332','État de choc. Principales étiologies : hypovolémique, septique (voir item 158), cardio-génique, anaphylactique'),
('IC-333','Situations exceptionnelles'),
('IC-334','Prise en charge immédiate pré-hospitalière et à l''arrivée à l''hôpital, évaluation des complications chez : un brûlé, un polytraumatisé, un traumatisé thoracique, un traumatisé abdominal, un traumatisé des membres et/ou du bassin, un traumatisé du rachis ou vertébro-médullaire, un traumatisé crânien ou crânio-encéphalique'),
('IC-335','Orientation diagnostique et conduite à tenir devant un traumatisme crânio-facial et oculaire'),
('IC-336','Coma non traumatique chez l''adulte et chez l''enfant'),
('IC-337','Principales intoxications aiguës'),
('IC-338','Œdème de Quincke et anaphylaxie'),
('IC-339','Syndromes coronariens aigus'),
('IC-340','Accidents vasculaires cérébraux'),
('IC-341','Hémorragie méningée'),
('IC-342','Malaise, perte de connaissance, crise comitiale chez l''adulte (voir item 105)'),
('IC-343','État confusionnel et trouble de conscience chez l''adulte et chez l''enfant'),
('IC-344','Prise en charge d''une patiente atteinte de pré-éclampsie'),
('IC-345','Malaise grave du nourrisson et mort inattendue du nourrisson'),
('IC-346','Convulsions chez le nourrisson et chez l''enfant'),
('IC-347','Rétention aiguë d''urine'),
('IC-348','Insuffisance rénale aiguë - Anurie'),
('IC-349','Infection aiguë des parties molles (abcès, panaris, phlegmon des gaines)'),
('IC-350','Grosse jambe rouge aiguë'),
('IC-351','Agitation et délire aigu'),
('IC-352','Crise d''angoisse aiguë et attaque de panique'),
('IC-353','Risque et conduite suicidaires chez l''enfant, l''adolescent et l''adulte : identification et prise en charge'),
('IC-354','Syndrome occlusif de l''enfant et de l''adulte'),
('IC-355','Hémorragie digestive'),
('IC-356','Appendicite de l''enfant et de l''adulte'),
('IC-357','Péritonite aiguë chez l''enfant et chez l''adulte'),
('IC-358','Pancréatite aiguë'),
('IC-359','Détresse et insuffisance respiratoire aigüe du nourrisson, de l''enfant et de l''adulte'),
('IC-360','Pneumothorax'),
('IC-361','Lésions péri-articulaires et ligamentaires du genou, de la cheville et de l''épaule'),
('IC-362','Prothèses et ostéosynthèses'),
('IC-363','Fractures fréquentes de l''adulte et du sujet âgé'),
('IC-364','Fractures chez l''enfant : particularités épidémiologiques, diagnostiques et thérapeutiques'),
('IC-365','Surveillance d''un malade sous plâtre/résine'),
('IC-366','Exposition accidentelle aux liquides biologiques : conduite à tenir'),
('IC-367','Impact de l''environnement sur la santé');

UPDATE public.edn_items_complete c
   SET title = u.title, updated_at = now()
  FROM uness_items u
 WHERE c.item_code = u.item_code
   AND c.title IS DISTINCT FROM u.title;

UPDATE public.edn_items_immersive c
   SET title = u.title, updated_at = now()
  FROM uness_items u
 WHERE c.item_code = u.item_code
   AND c.title IS DISTINCT FROM u.title;

DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n
    FROM public.edn_items_complete c JOIN uness_items u USING (item_code)
   WHERE c.title IS DISTINCT FROM u.title;
  IF n <> 0 THEN RAISE EXCEPTION '% titres ne correspondent toujours pas a UNESS', n; END IF;
END $$;

COMMIT;
